name: chestore2
description: CheStore MVP - classifieds app (Flutter + Supabase)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.5.6

  # State
  provider: ^6.1.2

  # Maps / location
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0

  # Utils
  uuid: ^4.5.1
  intl: ^0.19.0
  timeago: ^3.7.0

  # UI / media
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

  # Network
  url_launcher: ^6.3.0
  dio: ^5.9.1
  share_plus: ^12.0.1  # ✅ Совместимая версия

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true